service: facegrade-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  timeout: 30
  memorySize: 512
  role: arn:aws:iam::893411366350:role/LabRole
  environment:
    DYNAMODB_TABLE: StudentGrades
    REKOGNITION_COLLECTION: student-faces

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
